import { assets } from "@/assets";

const latestOffers = [
  {
    brand: "Mamas & Papas",
    image: assets.brand1,
    discount: "45% off",
    category: "Fashion",
    expiresIn: "52 days",
    couponText: "Show Coupon",
  },
  {
    brand: "Sivvi",
    image: assets.brand2,
    discount: "75% Off",
    category: "Electronics",
    expiresIn: "52 days",
    couponText: "Show Coupon",
  },
  {
    brand: "Cairo Cart",
    image: assets.brand3,
    discount: "65% off",
    category: "Beauty",
    expiresIn: "52 days",
    couponText: "Show Coupon",
  },
  {
    brand: "Noon",
    image: assets.brand1,
    discount: "45% off",
    category: "Study Products",
    expiresIn: "52 days",
    couponText: "Show Coupon",
  },
  {
    brand: "Sivvi",
    image: assets.brand2,
    discount: "75% Off",
    category: "Electronics",
    expiresIn: "52 days",
    couponText: "Show Coupon",
  },
  {
    brand: "Cairo Cart",
    image: assets.brand3,
    discount: "45% off",
    category: "Beauty",
    expiresIn: "52 days",
    couponText: "Show Coupon",
  },
  {
    brand: "Noon",
    image: assets.brand1,
    discount: "45% off",
    category: "Study Products",
    expiresIn: "52 days",
    couponText: "Show Coupon",
  },
  {
    brand: "Mamas & Papas",
    image: assets.brand2,
    discount: "45% off",
    category: "Fashion",
    expiresIn: "52 days",
    couponText: "Show Coupon",
  },
  {
    brand: "Cairo Cart",
    image: assets.brand3,
    discount: "45% off",
    category: "Beauty",
    expiresIn: "52 days",
    couponText: "Show Coupon",
  },
  {
    brand: "Noon",
    image: assets.brand1,
    discount: "45% off",
    category: "Study Products",
    expiresIn: "52 days",
    couponText: "Show Coupon",
  },
];
export default latestOffers;
